apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 namespace: istio-system
 name: xxx
spec:
 secretName: tls-cert
 issuerRef:
   name: clusterissuer
   kind: ClusterIssuer
 dnsNames:
   - tls.barakota.net
