apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 namespace: istio-system
 name: tls-istio-cert
spec:
 secretName: tls-istio-secret
 issuerRef:
   name: clusterissuer
   kind: ClusterIssuer
 dnsNames:
   - tls.barakota.net
