apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: PLACEHOLDER_REPLICAS
  template:
    spec:
      containers:
        - name: my-container
          image: PLACEHOLDER_IMAGE
