apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: my-app
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: app-variables-cm
      namespace: default    
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true    
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: ${IMAGE}
